### PR TITLE
Added onProgress function and made some code refactors

### PR DESCRIPTION
**Pull request by Azrideus**
tests are included
sorry for the formatting changes but my IDE is enforcing this code style ( semi , indent ... )

### CODE REVIEW

**Comment by marcuspoehls** [comment]
@Azrideus Thank you for the pull request. I can't merge it in this state. Please don't change the code styling in all files. You even changed linting rules to ensure your style.

Can you please refine this PR to only include the changes for the onProgress handler without reformatting everything.

You can also open a new pull request if it's to much to revert all other changes.

With all the noise it's hard to review the actual changes.

**Comment by Azrideus** [comment]
sorry it was my first ever PR  , I should have know that
Ill try to fix the formatting and will create another pr

**Comment by marcuspoehls** [comment]
Thank you 😊

Question: why can't you use the "process" method to show a progress bar? Do you want an explicit "onPostProcess" method to be sure the item was processed, either successful or with a failure? Basically a combination of "process" and "onError"?

**Comment by marcuspoehls** [comment]
@Azrideus Hey, are you still in need of this feature? Can you make some time available to proceed on this pull request?

**Comment by marcuspoehls** [comment]
@Azrideus Closing this PR here. Please feel free to re-open the merge request

**Pull request closed without merging**
