### PR TITLE
Use corresponding results

### PR DESCRIPTION
**Pull request by marcuspoehls**
Originally authored by @tylercollier in #57

### CODE REVIEW

**Comment by tylercollier** [comment]
What us the timeline for this change to be published in a new release?

**Comment by marcuspoehls** [comment]
@tylercollier Hey Tyler, I want to write the docs section for the merged timeout feature. It’s now possible to time out a task after x milliseconds. Once that’s done, I’ll publish a new release. Thank you for your patience 🤝

**Comment by damassi** [comment]
@marcuspoehls - would you mind publishing the release with timeout feature and then writing docs?

**Comment by marcuspoehls** [comment]
I’ve published version `2.4.0` to NPM. It contains the option to configure corresponding results 😃 

@tylercollier Thank you very much Tyler for your help on this!

**Comment by tylercollier** [comment]
I just upgraded my code in production to use it. It's awesome! It helped me reduce the lines of code needed and makes the code more readable. Thank you!

**Comment by marcuspoehls** [comment]
@tylercollier that’s awesome 😍

**Pull request merged**
